#!/bin/zsh

funcgtion help() {
    echo "Usage: ywait [-t timeout] pid"
    echo ""
    echo "Options:"
    echo "  -t, --timeout <seconds>  Specify a timeout in seconds. (default: 0)"
    echo "  -h, --help               Display this help message."
}

timeout=0

while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do case $1 in
  -t | --timeout )
    shift; timeout=$1
    ;;
  -h | --help )
    help
    exit 0
    ;;
esac; shift; done
if [[ "$1" == '--' ]]; then shift; fi

if [[ -z "$1" ]]; then
    pid=$(ps -e -o pid,command | grep -v '[y]wait$' | fzf --exact --header="Select a process by PID" | awk '{print $1}')
else
    pid=${1:?}
fi

kill -0 ${pid:?} || exit 1

start_time=$(date +%s)

while kill -0 ${pid:?} 2>/dev/null; do
    if [[ $timeout -gt 0 ]]; then
        current_time=$(date +%s)
        elapsed_time=$((current_time - start_time))
        if [[ $elapsed_time -ge $timeout ]]; then
            echo "Timeout reached" >&2
            exit 1
        fi
    fi
    sleep 1
done

